apiVersion: v1
kind: Service
metadata:
  name: nodejs-express
  namespace: nodejs-express
  labels:
    app: nodejs-express
spec:
  type: ClusterIP
  selector:
    app: nodejs-express
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
